add main loop

diff --git a/setwp b/setwp
--- a/setwp
+++ b/setwp
@@ -36,15 +36,18 @@ cycle () {
 		echo "Invalid time used: t was '$t', now set to '600'"
 		t=600
 	fi
-	for file in $d/{*.png,*.jpg,*.jpeg}
+	for ((;;))
 	do
-		swp $file
-		sleep $t
-		if [ ! $? -eq 0 ]
-		then
-			echo "An error occured in cycle, did you set time to a valid number?"
-			exit 1
-		fi
+		for file in $d/{*.png,*.jpg,*.jpeg}
+		do
+			swp $file
+			sleep $t
+			if [ ! $? -eq 0 ]
+			then
+				echo "An error occured in cycle, did you set time to a valid number?"
+				exit 1
+			fi
+		done
 	done
 }
 
