setwp now has functionality of testwp

diff --git a/setwp b/setwp
--- a/setwp
+++ b/setwp
@@ -52,6 +52,40 @@ cycle () {
 	done
 }
 
+# Downloads and sets a wallpaper, provides an option to save permanently.
+# Usage: download "$url"
+download ()
+{
+	ftype=$(basename "$1" | cut -d\. -f 2)
+	file=/tmp/"testwp.$ftype"
+	curl -s "$1" > "$file"
+
+	if ! swp "$file" > /dev/null 2>&1
+	then
+		echo "An error occured, is this a valid picture link?"
+		exit $?
+	fi
+
+	read -rp "Save? Y/N: " input
+	[[ ! "$input" =~ ^(y|Y)(es)?$ ]] && exit # Exit if we not saving
+
+	read -rp "Name (Empty for random name): " name
+	[ -z "$name" ] && name=$(tr -dc 0-9A-Za-z < /dev/random | head -c 15)
+	read -rep "Path (Empty for curr dir): " save
+	[ -z "$save" ] && save=.
+	save=$(realpath "${save%/}")
+
+	if [ -f "$save/$name.$ftype" ]
+	then
+		read -rp "This file already exist! Proceed? Y/N: " input
+		[[ "$input" =~ ^(n|N)(o)?$ ]] && echo "Save aborted." && exit 0
+	fi
+
+	echo "Saving! $save/$name.$ftype"
+	mv "$file" "$save/$name.$ftype"
+	exit
+}
+
 main ()
 {
 	last=$((${#args[@]} - 1))
@@ -81,6 +115,8 @@ main ()
 				;;
 		esac
 	done
+
+	[[ "$file" =~ ^http[s]?:// ]] && download "$file" # Check that it is a url
 
 	[ -z "$file" ] && echo "Invalid file, see -h" && exit 1
 
